In [1]:
data = {'ID': 1, 'Name': 'Alice', 'Age': 25}
data

{'ID': 1, 'Name': 'Alice', 'Age': 25}

In [2]:
type(data)

dict

In [4]:
print(len(data))

3

In [5]:
import polars as pl
#pl.show_versions()
df = pl.DataFrame(data)
df

shape: (1, 3)
┌─────┬───────┬─────┐
│ ID  ┆ Name  ┆ Age │
│ --- ┆ ---   ┆ --- │
│ i64 ┆ str   ┆ i64 │
╞═════╪═══════╪═════╡
│ 1   ┆ Alice ┆ 25  │
└─────┴───────┴─────┘

In [6]:
type(df)

polars.dataframe.frame.DataFrame

In [7]:
df.columns

['ID', 'Name', 'Age']

In [8]:
len(df)

1

In [10]:
n_data = [[1, 'Alice', 25]]
print(n_data)
print(len(n_data))
print(type(n_data))

[[1, 'Alice', 25]]
1
<class 'list'>

In [14]:
df = pl.DataFrame(n_data, schema=['ID', 'Name', 'Age'], orient="row")
df

shape: (1, 3)
┌─────┬───────┬─────┐
│ ID  ┆ Name  ┆ Age │
│ --- ┆ ---   ┆ --- │
│ i64 ┆ str   ┆ i64 │
╞═════╪═══════╪═════╡
│ 1   ┆ Alice ┆ 25  │
└─────┴───────┴─────┘

In [16]:
print(type(df))
print(len(df))

<class 'polars.dataframe.frame.DataFrame'>
1

In [17]:
c_data = {
    'Scores': [[85, 90, 95], [88, 82, 75], [84, 98, 92]],
    'Name': ['Alice',  'Bob', 'Charlie'],
    'Age': [25, 36, 35],
    'Details': [
        {"City": 'New York', 'job': "Engineer"},
        {"City": 'LoasAngeles', 'job': "Artist"},
        {"City": 'chicago', 'job': "Doctor"}
    ]
}

In [23]:
import pandas as pd
df_pandas = pd.DataFrame(c_data)
print(df_pandas.dtypes)
print(type(df_pandas))
df_pandas

Scores     object
Name       object
Age         int64
Details    object
dtype: object
<class 'pandas.core.frame.DataFrame'>

         Scores     Name  Age                                   Details
0  [85, 90, 95]    Alice   25   {'City': 'New York', 'job': 'Engineer'}
1  [88, 82, 75]      Bob   36  {'City': 'LoasAngeles', 'job': 'Artist'}
2  [84, 98, 92]  Charlie   35      {'City': 'chicago', 'job': 'Doctor'}

In [24]:
df_polars = pl.DataFrame(c_data)
print(type(df_polars))
df_polars

<class 'polars.dataframe.frame.DataFrame'>

shape: (3, 4)
┌──────────────┬─────────┬─────┬──────────────────────────┐
│ Scores       ┆ Name    ┆ Age ┆ Details                  │
│ ---          ┆ ---     ┆ --- ┆ ---                      │
│ list[i64]    ┆ str     ┆ i64 ┆ struct[2]                │
╞══════════════╪═════════╪═════╪══════════════════════════╡
│ [85, 90, 95] ┆ Alice   ┆ 25  ┆ {"New York","Engineer"}  │
│ [88, 82, 75] ┆ Bob     ┆ 36  ┆ {"LoasAngeles","Artist"} │
│ [84, 98, 92] ┆ Charlie ┆ 35  ┆ {"chicago","Doctor"}     │
└──────────────┴─────────┴─────┴──────────────────────────┘

In [26]:
df_from_pandas = pl.from_pandas(df_pandas)
print(type(df_from_pandas))
df_from_pandas

<class 'polars.dataframe.frame.DataFrame'>

shape: (3, 4)
┌──────────────┬─────────┬─────┬──────────────────────────┐
│ Scores       ┆ Name    ┆ Age ┆ Details                  │
│ ---          ┆ ---     ┆ --- ┆ ---                      │
│ list[i64]    ┆ str     ┆ i64 ┆ struct[2]                │
╞══════════════╪═════════╪═════╪══════════════════════════╡
│ [85, 90, 95] ┆ Alice   ┆ 25  ┆ {"New York","Engineer"}  │
│ [88, 82, 75] ┆ Bob     ┆ 36  ┆ {"LoasAngeles","Artist"} │
│ [84, 98, 92] ┆ Charlie ┆ 35  ┆ {"chicago","Doctor"}     │
└──────────────┴─────────┴─────┴──────────────────────────┘

In [27]:
df_to_pandas = df_polars.to_pandas()
print(type(df_to_pandas))
df_to_pandas

<class 'pandas.core.frame.DataFrame'>

         Scores     Name  Age                                   Details
0  [85, 90, 95]    Alice   25   {'City': 'New York', 'job': 'Engineer'}
1  [88, 82, 75]      Bob   36  {'City': 'LoasAngeles', 'job': 'Artist'}
2  [84, 98, 92]  Charlie   35      {'City': 'chicago', 'job': 'Doctor'}

In [29]:
#LAZY
df = pl.DataFrame({"name": ["Alice", "Bob", "Charlie"], "age": [25, 30, 35]})
lazy_df = df.lazy() # Convert to lazy mode 
filtered_lazy_df = lazy_df.filter(pl.col("age") > 28) # No execution yet! 
result = filtered_lazy_df.collect() 
print(result)
print(type(result))

shape: (2, 2)
┌─────────┬─────┐
│ name    ┆ age │
│ ---     ┆ --- │
│ str     ┆ i64 │
╞═════════╪═════╡
│ Bob     ┆ 30  │
│ Charlie ┆ 35  │
└─────────┴─────┘
<class 'polars.dataframe.frame.DataFrame'>

# Why Use Lazy Mode?
- Faster Execution: Polars avoids unnecessary computations, making it faster for large datasets.
- Better Memory Management: It processes data in chunks instead of keeping everything in memory.
- Smart Query Optimization: It can rearrange operations for better efficiency, like pushing filters earlier to reduce the amount of data processed.

## When to Use Lazy Mode?
- Working with large datasets (millions or billions of rows).
- Running complex queries involving multiple operations.
- Needing efficient memory usage to avoid crashes.

In [31]:
csv_path = './Files/Sample_Superstore.csv'
csv_df = pl.read_csv(csv_path)
csv_df

shape: (9_994, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ CA-2016-15215 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ …      ┆ …             ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 9990   ┆ CA-2014-11042 ┆ 21-01-2014 ┆ 23-01-2014 ┆ … ┆ 25.248   ┆ 3        ┆ 0.2      ┆ 4.1028   │
│        ┆ 2             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 9991   ┆ CA-2017-12125 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 91.96    ┆ 2        ┆ 0.0      ┆ 15.6332  │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 9992   ┆ CA-2017-12125 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 258.576  ┆ 2        ┆ 0.2      ┆ 19.3932  │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 9993   ┆ CA-2017-12125 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 29.6     ┆ 4        ┆ 0.0      ┆ 13.32    │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 9994   ┆ CA-2017-11991 ┆ 04-05-2017 ┆ 09-05-2017 ┆ … ┆ 243.16   ┆ 2        ┆ 0.0      ┆ 72.948   │
│        ┆ 4             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [32]:
print(type(csv_df))

<class 'polars.dataframe.frame.DataFrame'>

In [33]:
csv_df['Profit'].head()

shape: (10,)
Series: 'Profit' [f64]
[
	41.9136
	219.582
	6.8714
	-383.031
	2.5164
	14.1694
	1.9656
	90.7152
	5.7825
	34.47
]

In [35]:
print(type(csv_df['Profit'].head()))

<class 'polars.series.series.Series'>

In [36]:
csv_df.select('Profit').to_series().head(3)

shape: (3,)
Series: 'Profit' [f64]
[
	41.9136
	219.582
	6.8714
]

In [37]:
s = csv_df['Customer_Name']
s.to_frame().head(3)

shape: (3, 1)
┌─────────────────┐
│ Customer_Name   │
│ ---             │
│ str             │
╞═════════════════╡
│ Claire Gute     │
│ Claire Gute     │
│ Darrin Van Huff │
└─────────────────┘

In [38]:
s

shape: (9_994,)
Series: 'Customer_Name' [str]
[
	"Claire Gute"
	"Claire Gute"
	"Darrin Van Huff"
	"Sean O'Donnell"
	"Sean O'Donnell"
	…
	"Tom Boeckenhauer"
	"Dave Brooks"
	"Dave Brooks"
	"Dave Brooks"
	"Chris Cortes"
]

# Series or Dataframe from `list` or `dict`

In [39]:
val = [1,2,3]
print(val, type(val))

[1, 2, 3] <class 'list'>

In [41]:
pl.Series(val)

shape: (3,)
Series: '' [i64]
[
	1
	2
	3
]

In [42]:
pl.Series('vals', val)

shape: (3,)
Series: 'vals' [i64]
[
	1
	2
	3
]

In [43]:
pl.Series(name='vals', values=val).to_list()

[1, 2, 3]

In [44]:
import numpy as np

csv_df.to_numpy()

array([[1, None, None, ..., 2, 0.0, 41.9136],
       [2, 'CA-2016-152156', '08-11-2016', ..., 3, 0.0, 219.582],
       [3, 'CA-2016-138688', '12-06-2016', ..., 2, 0.0, 6.8714],
       ...,
       [9992, 'CA-2017-121258', '26-02-2017', ..., 2, 0.2, 19.3932],
       [9993, 'CA-2017-121258', '26-02-2017', ..., 4, 0.0, 13.32],
       [9994, 'CA-2017-119914', '04-05-2017', ..., 2, 0.0, 72.948]],
      shape=(9994, 21), dtype=object)

In [46]:
f_array = csv_df.select(pl.col(pl.Float64)).to_numpy()
f_array

array([[2.61960e+02, 0.00000e+00, 4.19136e+01],
       [7.31940e+02, 0.00000e+00, 2.19582e+02],
       [1.46200e+01, 0.00000e+00, 6.87140e+00],
       ...,
       [2.58576e+02, 2.00000e-01, 1.93932e+01],
       [2.96000e+01, 0.00000e+00, 1.33200e+01],
       [2.43160e+02, 0.00000e+00, 7.29480e+01]], shape=(9994, 3))

In [48]:
l_df = pl.DataFrame(f_array.tolist())
print(type(l_df))
l_df

<class 'polars.dataframe.frame.DataFrame'>

shape: (3, 9_994)
┌──────────┬──────────┬──────────┬──────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ column_0 ┆ column_1 ┆ column_2 ┆ column_3 ┆ … ┆ column_999 ┆ column_999 ┆ column_999 ┆ column_99 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ 0          ┆ 1          ┆ 2          ┆ 93        │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│          ┆          ┆          ┆          ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64       │
╞══════════╪══════════╪══════════╪══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 261.96   ┆ 731.94   ┆ 14.62    ┆ 957.5775 ┆ … ┆ 91.96      ┆ 258.576    ┆ 29.6       ┆ 243.16    │
│ 0.0      ┆ 0.0      ┆ 0.0      ┆ 0.45     ┆ … ┆ 0.0        ┆ 0.2        ┆ 0.0        ┆ 0.0       │
│ 41.9136  ┆ 219.582  ┆ 6.8714   ┆ -383.031 ┆ … ┆ 15.6332    ┆ 19.3932    ┆ 13.32      ┆ 72.948    │
└──────────┴──────────┴──────────┴──────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [49]:
csv_df['Profit'].to_numpy()#zero copy = read only possible if no nan or null is present

array([ 41.9136, 219.582 ,   6.8714, ...,  19.3932,  13.32  ,  72.948 ],
      shape=(9994,))

In [50]:
csv_df['Profit'].to_numpy(allow_copy=False) #fails

RuntimeError: copy not allowed: cannot convert to a NumPy array without copying data

*allow_copy=True (Default): Polars extracts data as a zero-copy view if possible. If the data layout requires adjustments (like merging multi-chunk columns or rewriting data types), it will quietly clone the data in memory to build the array.allow_copy=False: Polars will only succeed if it can point NumPy directly to its existing Apache Arrow memory structures without duplication. If a copy is required, it immediately throws an exception*

# Data types

In [51]:
df = pl.DataFrame({
    "integer_column": [1, 2, 3, 4, 5],  # Default: Int64
    "float_column": [1.1, 2.2, 3.3, 4.4, 5.5]  # Default: Float64
})
 
print("DataFrame:")
print(df)
 
print("\nData Types:")
print(df.schema)

DataFrame:
shape: (5, 2)
┌────────────────┬──────────────┐
│ integer_column ┆ float_column │
│ ---            ┆ ---          │
│ i64            ┆ f64          │
╞════════════════╪══════════════╡
│ 1              ┆ 1.1          │
│ 2              ┆ 2.2          │
│ 3              ┆ 3.3          │
│ 4              ┆ 4.4          │
│ 5              ┆ 5.5          │
└────────────────┴──────────────┘

Data Types:
Schema({'integer_column': Int64, 'float_column': Float64})

In [52]:
df = df.with_columns([
    df["integer_column"].cast(pl.Int32),
    df["float_column"].cast(pl.Float32)
])
 
print("\nUpdated Data Types:")
print(df.schema)

Updated Data Types:
Schema({'integer_column': Int32, 'float_column': Float32})

In [53]:
# For very large numbers, use Int64 or UInt64:
df_large = pl.DataFrame({
    "big_number": [10**12, 10**13, 10**14]  # Large integers
}).with_columns(pl.col("big_number").cast(pl.Int64))
 
print("\nLarge Number Data Types:")
print(df_large.schema)

Large Number Data Types:
Schema({'big_number': Int64})

In [54]:
df = df.with_columns(
    (df["float_column"] * 3.14159).alias("pi_multiplication")
)
 
print("\nResult with Precision:")
print(df)

Result with Precision:
shape: (5, 3)
┌────────────────┬──────────────┬───────────────────┐
│ integer_column ┆ float_column ┆ pi_multiplication │
│ ---            ┆ ---          ┆ ---               │
│ i32            ┆ f32          ┆ f32               │
╞════════════════╪══════════════╪═══════════════════╡
│ 1              ┆ 1.1          ┆ 3.455749          │
│ 2              ┆ 2.2          ┆ 6.911499          │
│ 3              ┆ 3.3          ┆ 10.367248         │
│ 4              ┆ 4.4          ┆ 13.822997         │
│ 5              ┆ 5.5          ┆ 17.278746         │
└────────────────┴──────────────┴───────────────────┘

In [55]:
df.describe()

shape: (9, 4)
┌────────────┬────────────────┬──────────────┬───────────────────┐
│ statistic  ┆ integer_column ┆ float_column ┆ pi_multiplication │
│ ---        ┆ ---            ┆ ---          ┆ ---               │
│ str        ┆ f64            ┆ f64          ┆ f64               │
╞════════════╪════════════════╪══════════════╪═══════════════════╡
│ count      ┆ 5.0            ┆ 5.0          ┆ 5.0               │
│ null_count ┆ 0.0            ┆ 0.0          ┆ 0.0               │
│ mean       ┆ 3.0            ┆ 3.3          ┆ 10.367248         │
│ std        ┆ 1.581139       ┆ 1.739253     ┆ 5.464019          │
│ min        ┆ 1.0            ┆ 1.1          ┆ 3.455749          │
│ 25%        ┆ 2.0            ┆ 2.2          ┆ 6.911499          │
│ 50%        ┆ 3.0            ┆ 3.3          ┆ 10.367248         │
│ 75%        ┆ 4.0            ┆ 4.4          ┆ 13.822997         │
│ max        ┆ 5.0            ┆ 5.5          ┆ 17.278746         │
└────────────┴────────────────┴──────────────┴───────────────────┘