In [ ]:
#Selecting with [] saves memory

In [2]:
import polars as pl

store = pl.read_csv('./Files/Sample_Superstore.csv')
store

shape: (9_994, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ CA-2016-15215 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ …      ┆ …             ┆ …          ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 9990   ┆ CA-2014-11042 ┆ 21-01-2014 ┆ 23-01-2014 ┆ … ┆ 25.248   ┆ 3        ┆ 0.2      ┆ 4.1028   │
│        ┆ 2             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 9991   ┆ CA-2017-12125 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 91.96    ┆ 2        ┆ 0.0      ┆ 15.6332  │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 9992   ┆ CA-2017-12125 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 258.576  ┆ 2        ┆ 0.2      ┆ 19.3932  │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 9993   ┆ CA-2017-12125 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 29.6     ┆ 4        ┆ 0.0      ┆ 13.32    │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 9994   ┆ CA-2017-11991 ┆ 04-05-2017 ┆ 09-05-2017 ┆ … ┆ 243.16   ┆ 2        ┆ 0.0      ┆ 72.948   │
│        ┆ 4             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [4]:
store.head(3)

shape: (3, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 1      ┆ null           ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96 ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 3      ┆ CA-2016-138688 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62  ┆ 2        ┆ 0.0      ┆ 6.8714  │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

In [6]:
print(type(store['Profit'].head()))
store['Profit'].head()

<class 'polars.series.series.Series'>

shape: (10,)
Series: 'Profit' [f64]
[
	41.9136
	219.582
	6.8714
	-383.031
	2.5164
	14.1694
	1.9656
	90.7152
	5.7825
	34.47
]

In [7]:
fst = store[0, 'Profit'] #Select first value of column Profit
print(fst, type(fst))

41.9136 <class 'float'>

In [8]:
#All rows but some columns
store[:, 1:6].head(2) #columns 1 - 5

shape: (2, 5)
┌────────────────┬────────────┬────────────┬──────────────┬─────────────┐
│ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ Ship_Mode    ┆ Customer_ID │
│ ---            ┆ ---        ┆ ---        ┆ ---          ┆ ---         │
│ str            ┆ str        ┆ str        ┆ str          ┆ str         │
╞════════════════╪════════════╪════════════╪══════════════╪═════════════╡
│ null           ┆ null       ┆ 11-11-2016 ┆ Second Class ┆ CG-12520    │
│ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ Second Class ┆ CG-12520    │
└────────────────┴────────────┴────────────┴──────────────┴─────────────┘

In [10]:
sel = store.select('Profit').head()
print(type(sel))
sel #to_series

<class 'polars.dataframe.frame.DataFrame'>

shape: (5, 1)
┌──────────┐
│ Profit   │
│ ---      │
│ f64      │
╞══════════╡
│ 41.9136  │
│ 219.582  │
│ 6.8714   │
│ -383.031 │
│ 2.5164   │
└──────────┘

In [11]:
sel = store.select(pl.col('Profit')).head()
print(sel.to_series())
sel #sel.round(0).head()

shape: (5,)
Series: 'Profit' [f64]
[
	41.9136
	219.582
	6.8714
	-383.031
	2.5164
]

shape: (5, 1)
┌──────────┐
│ Profit   │
│ ---      │
│ f64      │
╞══════════╡
│ 41.9136  │
│ 219.582  │
│ 6.8714   │
│ -383.031 │
│ 2.5164   │
└──────────┘

In [12]:
store[['Customer_Name', 'Profit']].head()

shape: (5, 2)
┌─────────────────┬──────────┐
│ Customer_Name   ┆ Profit   │
│ ---             ┆ ---      │
│ str             ┆ f64      │
╞═════════════════╪══════════╡
│ Claire Gute     ┆ 41.9136  │
│ Claire Gute     ┆ 219.582  │
│ Darrin Van Huff ┆ 6.8714   │
│ Sean O'Donnell  ┆ -383.031 │
│ Sean O'Donnell  ┆ 2.5164   │
└─────────────────┴──────────┘

In [13]:
store[[0, 1], ['Customer_Name', 'Profit']]

shape: (2, 2)
┌───────────────┬─────────┐
│ Customer_Name ┆ Profit  │
│ ---           ┆ ---     │
│ str           ┆ f64     │
╞═══════════════╪═════════╡
│ Claire Gute   ┆ 41.9136 │
│ Claire Gute   ┆ 219.582 │
└───────────────┴─────────┘

In [14]:
store[1:3]

shape: (2, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 3      ┆ CA-2016-138688 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62  ┆ 2        ┆ 0.0      ┆ 6.8714  │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

In [15]:
store.select('Customer_Name', 'Profit').head() #or list[col1, col2] or pl.col(), pl.col()

shape: (5, 2)
┌─────────────────┬──────────┐
│ Customer_Name   ┆ Profit   │
│ ---             ┆ ---      │
│ str             ┆ f64      │
╞═════════════════╪══════════╡
│ Claire Gute     ┆ 41.9136  │
│ Claire Gute     ┆ 219.582  │
│ Darrin Van Huff ┆ 6.8714   │
│ Sean O'Donnell  ┆ -383.031 │
│ Sean O'Donnell  ┆ 2.5164   │
└─────────────────┴──────────┘

In [16]:
store.select(pl.all()).head(3)

shape: (3, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 1      ┆ null           ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96 ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 3      ┆ CA-2016-138688 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62  ┆ 2        ┆ 0.0      ┆ 6.8714  │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

In [18]:
store.select(pl.exclude('Postal_Code', 'Quantity')).head(3)

shape: (3, 19)
┌────────┬──────────────┬────────────┬────────────┬───┬──────────────┬────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID     ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Product_Name ┆ Sales  ┆ Discount ┆ Profit  │
│ ---    ┆ ---          ┆ ---        ┆ ---        ┆   ┆ ---          ┆ ---    ┆ ---      ┆ ---     │
│ i64    ┆ str          ┆ str        ┆ str        ┆   ┆ str          ┆ f64    ┆ f64      ┆ f64     │
╞════════╪══════════════╪════════════╪════════════╪═══╪══════════════╪════════╪══════════╪═════════╡
│ 1      ┆ null         ┆ null       ┆ 11-11-2016 ┆ … ┆ Bush         ┆ 261.96 ┆ 0.0      ┆ 41.9136 │
│        ┆              ┆            ┆            ┆   ┆ Somerset     ┆        ┆          ┆         │
│        ┆              ┆            ┆            ┆   ┆ Collection   ┆        ┆          ┆         │
│        ┆              ┆            ┆            ┆   ┆ Bookc…       ┆        ┆          ┆         │
│ 2      ┆ CA-2016-1521 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ Hon Deluxe   ┆ 731.94 ┆ 0.0      ┆ 219.582 │
│        ┆ 56           ┆            ┆            ┆   ┆ Fabric       ┆        ┆          ┆         │
│        ┆              ┆            ┆            ┆   ┆ Upholstered  ┆        ┆          ┆         │
│        ┆              ┆            ┆            ┆   ┆ …            ┆        ┆          ┆         │
│ 3      ┆ CA-2016-1386 ┆ 12-06-2016 ┆ null       ┆ … ┆ Self-Adhesiv ┆ 14.62  ┆ 0.0      ┆ 6.8714  │
│        ┆ 88           ┆            ┆            ┆   ┆ e Address    ┆        ┆          ┆         │
│        ┆              ┆            ┆            ┆   ┆ Labels f…    ┆        ┆          ┆         │
└────────┴──────────────┴────────────┴────────────┴───┴──────────────┴────────┴──────────┴─────────┘

In [19]:
store.select('^P.*$') #REGEX SELECTION  store.select(pl.col('^P.*$'))

shape: (9_994, 4)
┌─────────────┬─────────────────┬─────────────────────────────────┬──────────┐
│ Postal_Code ┆ Product_ID      ┆ Product_Name                    ┆ Profit   │
│ ---         ┆ ---             ┆ ---                             ┆ ---      │
│ i64         ┆ str             ┆ str                             ┆ f64      │
╞═════════════╪═════════════════╪═════════════════════════════════╪══════════╡
│ 42420       ┆ FUR-BO-10001798 ┆ Bush Somerset Collection Bookc… ┆ 41.9136  │
│ 42420       ┆ FUR-CH-10000454 ┆ Hon Deluxe Fabric Upholstered … ┆ 219.582  │
│ 90036       ┆ OFF-LA-10000240 ┆ Self-Adhesive Address Labels f… ┆ 6.8714   │
│ 33311       ┆ FUR-TA-10000577 ┆ Bretford CR4500 Series Slim Re… ┆ -383.031 │
│ 33311       ┆ OFF-ST-10000760 ┆ Eldon Fold 'N Roll Cart System  ┆ 2.5164   │
│ …           ┆ …               ┆ …                               ┆ …        │
│ 33180       ┆ FUR-FU-10001889 ┆ Ultra Door Pull Handle          ┆ 4.1028   │
│ 92627       ┆ FUR-FU-10000747 ┆ Tenex B1-RE Series Chair Mats … ┆ 15.6332  │
│ 92627       ┆ TEC-PH-10003645 ┆ Aastra 57i VoIP phone           ┆ 19.3932  │
│ 92627       ┆ OFF-PA-10004041 ┆ It's Hot Message Books with St… ┆ 13.32    │
│ 92683       ┆ OFF-AP-10002684 ┆ Acco 7-Outlet Masterpiece Powe… ┆ 72.948   │
└─────────────┴─────────────────┴─────────────────────────────────┴──────────┘

In [22]:
store.select(pl.col(pl.Utf8)).head() #TYPE SELECTIOM

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Order_ID  ┆ Order_Dat ┆ Ship_Date ┆ Ship_Mode ┆ … ┆ Product_I ┆ Category  ┆ Sub_Categ ┆ Product_ │
│ ---       ┆ e         ┆ ---       ┆ ---       ┆   ┆ D         ┆ ---       ┆ ory       ┆ Name     │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ null      ┆ 11-11-201 ┆ Second    ┆ … ┆ FUR-BO-10 ┆ Furniture ┆ Bookcases ┆ Bush     │
│           ┆           ┆ 6         ┆ Class     ┆   ┆ 001798    ┆           ┆           ┆ Somerset │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Collecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ on       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Bookc…   │
│ CA-2016-1 ┆ 08-11-201 ┆ 11-11-201 ┆ Second    ┆ … ┆ FUR-CH-10 ┆ Furniture ┆ Chairs    ┆ Hon      │
│ 52156     ┆ 6         ┆ 6         ┆ Class     ┆   ┆ 000454    ┆           ┆           ┆ Deluxe   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Fabric   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Upholste │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ red …    │
│ CA-2016-1 ┆ 12-06-201 ┆ null      ┆ null      ┆ … ┆ OFF-LA-10 ┆ Office    ┆ Labels    ┆ Self-Adh │
│ 38688     ┆ 6         ┆           ┆           ┆   ┆ 000240    ┆ Supplies  ┆           ┆ esive    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Address  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Labels   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f…       │
│ null      ┆ 11-10-201 ┆ null      ┆ Standard  ┆ … ┆ FUR-TA-10 ┆ Furniture ┆ Tables    ┆ Bretford │
│           ┆ 5         ┆           ┆ Class     ┆   ┆ 000577    ┆           ┆           ┆ CR4500   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Series   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Slim Re… │
│ US-2015-1 ┆ 11-10-201 ┆ 18-10-201 ┆ Standard  ┆ … ┆ OFF-ST-10 ┆ Office    ┆ Storage   ┆ Eldon    │
│ 08966     ┆ 5         ┆ 5         ┆ Class     ┆   ┆ 000760    ┆ Supplies  ┆           ┆ Fold 'N  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Roll     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Cart     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ System   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
store.select(pl.col(pl.Float64, pl.Int64)).head()

shape: (5, 6)
┌────────┬─────────────┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Postal_Code ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---         ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ i64         ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═════════════╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ 42420       ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ 42420       ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│ 3      ┆ 90036       ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│ 4      ┆ 33311       ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ 33311       ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
└────────┴─────────────┴──────────┴──────────┴──────────┴──────────┘

# SELECTION API

In [28]:
import polars.selectors as cs
store.select(pl.selectors.all()).head(3)

shape: (3, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 1      ┆ null           ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96 ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 3      ┆ CA-2016-138688 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62  ┆ 2        ┆ 0.0      ┆ 6.8714  │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

In [29]:
store.select(cs.first()).head(3)#first columns

shape: (3, 1)
┌────────┐
│ Row_ID │
│ ---    │
│ i64    │
╞════════╡
│ 1      │
│ 2      │
│ 3      │
└────────┘

In [30]:
store.select(cs.all().max())

shape: (1, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 9994   ┆ US-2017-16955 ┆ 31-12-2016 ┆ 31-12-2017 ┆ … ┆ 22638.48 ┆ 14       ┆ 0.8      ┆ 8399.976 │
│        ┆ 1             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [32]:
store.select(cs.numeric()).head(3)

shape: (3, 6)
┌────────┬─────────────┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Postal_Code ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---         ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ i64         ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪═════════════╪════════╪══════════╪══════════╪═════════╡
│ 1      ┆ 42420       ┆ 261.96 ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ 42420       ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 3      ┆ 90036       ┆ 14.62  ┆ 2        ┆ 0.0      ┆ 6.8714  │
└────────┴─────────────┴────────┴──────────┴──────────┴─────────┘

In [33]:
store.select(~cs.numeric()).head(3)

shape: (3, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Order_ID  ┆ Order_Dat ┆ Ship_Date ┆ Ship_Mode ┆ … ┆ Product_I ┆ Category  ┆ Sub_Categ ┆ Product_ │
│ ---       ┆ e         ┆ ---       ┆ ---       ┆   ┆ D         ┆ ---       ┆ ory       ┆ Name     │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ null      ┆ 11-11-201 ┆ Second    ┆ … ┆ FUR-BO-10 ┆ Furniture ┆ Bookcases ┆ Bush     │
│           ┆           ┆ 6         ┆ Class     ┆   ┆ 001798    ┆           ┆           ┆ Somerset │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Collecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ on       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Bookc…   │
│ CA-2016-1 ┆ 08-11-201 ┆ 11-11-201 ┆ Second    ┆ … ┆ FUR-CH-10 ┆ Furniture ┆ Chairs    ┆ Hon      │
│ 52156     ┆ 6         ┆ 6         ┆ Class     ┆   ┆ 000454    ┆           ┆           ┆ Deluxe   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Fabric   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Upholste │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ red …    │
│ CA-2016-1 ┆ 12-06-201 ┆ null      ┆ null      ┆ … ┆ OFF-LA-10 ┆ Office    ┆ Labels    ┆ Self-Adh │
│ 38688     ┆ 6         ┆           ┆           ┆   ┆ 000240    ┆ Supplies  ┆           ┆ esive    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Address  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Labels   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f…       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [38]:
store.select(~cs.by_name('Country', 'State')).head(3)

shape: (3, 19)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 1      ┆ null           ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96 ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 3      ┆ CA-2016-138688 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62  ┆ 2        ┆ 0.0      ┆ 6.8714  │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

In [39]:
store.select(cs.starts_with('P')).head(2)

shape: (2, 4)
┌─────────────┬─────────────────┬─────────────────────────────────┬─────────┐
│ Postal_Code ┆ Product_ID      ┆ Product_Name                    ┆ Profit  │
│ ---         ┆ ---             ┆ ---                             ┆ ---     │
│ i64         ┆ str             ┆ str                             ┆ f64     │
╞═════════════╪═════════════════╪═════════════════════════════════╪═════════╡
│ 42420       ┆ FUR-BO-10001798 ┆ Bush Somerset Collection Bookc… ┆ 41.9136 │
│ 42420       ┆ FUR-CH-10000454 ┆ Hon Deluxe Fabric Upholstered … ┆ 219.582 │
└─────────────┴─────────────────┴─────────────────────────────────┴─────────┘

In [40]:
store.select(cs.starts_with('S', 'C')).head(2)

shape: (2, 11)
┌────────────┬────────────┬────────────┬───────────┬───┬──────────┬───────────┬───────────┬────────┐
│ Ship_Date  ┆ Ship_Mode  ┆ Customer_I ┆ Customer_ ┆ … ┆ State    ┆ Category  ┆ Sub_Categ ┆ Sales  │
│ ---        ┆ ---        ┆ D          ┆ Name      ┆   ┆ ---      ┆ ---       ┆ ory       ┆ ---    │
│ str        ┆ str        ┆ ---        ┆ ---       ┆   ┆ str      ┆ str       ┆ ---       ┆ f64    │
│            ┆            ┆ str        ┆ str       ┆   ┆          ┆           ┆ str       ┆        │
╞════════════╪════════════╪════════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪════════╡
│ 11-11-2016 ┆ Second     ┆ CG-12520   ┆ Claire    ┆ … ┆ Kentucky ┆ Furniture ┆ Bookcases ┆ 261.96 │
│            ┆ Class      ┆            ┆ Gute      ┆   ┆          ┆           ┆           ┆        │
│ 11-11-2016 ┆ Second     ┆ CG-12520   ┆ Claire    ┆ … ┆ Kentucky ┆ Furniture ┆ Chairs    ┆ 731.94 │
│            ┆ Class      ┆            ┆ Gute      ┆   ┆          ┆           ┆           ┆        │
└────────────┴────────────┴────────────┴───────────┴───┴──────────┴───────────┴───────────┴────────┘

In [41]:
store.select(cs.matches('Customer_Name|Profit')).head(2)

shape: (2, 2)
┌───────────────┬─────────┐
│ Customer_Name ┆ Profit  │
│ ---           ┆ ---     │
│ str           ┆ f64     │
╞═══════════════╪═════════╡
│ Claire Gute   ┆ 41.9136 │
│ Claire Gute   ┆ 219.582 │
└───────────────┴─────────┘

In [42]:
store.select(cs.string() | cs.starts_with('O')).head(2)

shape: (2, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Order_ID  ┆ Order_Dat ┆ Ship_Date ┆ Ship_Mode ┆ … ┆ Product_I ┆ Category  ┆ Sub_Categ ┆ Product_ │
│ ---       ┆ e         ┆ ---       ┆ ---       ┆   ┆ D         ┆ ---       ┆ ory       ┆ Name     │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ null      ┆ 11-11-201 ┆ Second    ┆ … ┆ FUR-BO-10 ┆ Furniture ┆ Bookcases ┆ Bush     │
│           ┆           ┆ 6         ┆ Class     ┆   ┆ 001798    ┆           ┆           ┆ Somerset │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Collecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ on       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Bookc…   │
│ CA-2016-1 ┆ 08-11-201 ┆ 11-11-201 ┆ Second    ┆ … ┆ FUR-CH-10 ┆ Furniture ┆ Chairs    ┆ Hon      │
│ 52156     ┆ 6         ┆ 6         ┆ Class     ┆   ┆ 000454    ┆           ┆           ┆ Deluxe   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Fabric   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Upholste │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ red …    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [43]:
store.select(cs.string() - cs.starts_with('O')).head(2)

shape: (2, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Ship_Date ┆ Ship_Mode ┆ Customer_ ┆ Customer_ ┆ … ┆ Product_I ┆ Category  ┆ Sub_Categ ┆ Product_ │
│ ---       ┆ ---       ┆ ID        ┆ Name      ┆   ┆ D         ┆ ---       ┆ ory       ┆ Name     │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 11-11-201 ┆ Second    ┆ CG-12520  ┆ Claire    ┆ … ┆ FUR-BO-10 ┆ Furniture ┆ Bookcases ┆ Bush     │
│ 6         ┆ Class     ┆           ┆ Gute      ┆   ┆ 001798    ┆           ┆           ┆ Somerset │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Collecti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ on       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Bookc…   │
│ 11-11-201 ┆ Second    ┆ CG-12520  ┆ Claire    ┆ … ┆ FUR-CH-10 ┆ Furniture ┆ Chairs    ┆ Hon      │
│ 6         ┆ Class     ┆           ┆ Gute      ┆   ┆ 000454    ┆           ┆           ┆ Deluxe   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Fabric   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Upholste │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ red …    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘