In [2]:
import polars as pl

st = pl.read_csv('./Files/Sample_Superstore.csv')

In [4]:
pl.read_csv('./Files/Sample_Superstore.csv').select('Profit').with_columns(pl.col('Profit').round(0)).head()

shape: (5, 1)
┌────────┐
│ Profit │
│ ---    │
│ f64    │
╞════════╡
│ 42.0   │
│ 220.0  │
│ 7.0    │
│ -383.0 │
│ 3.0    │
└────────┘

In [5]:
pl.read_csv(
    './Files/Sample_Superstore.csv'
    ).select('Profit').with_columns(
        pl.col('Profit').round(0).alias('roundProfit')
            ).head()

shape: (5, 2)
┌──────────┬─────────────┐
│ Profit   ┆ roundProfit │
│ ---      ┆ ---         │
│ f64      ┆ f64         │
╞══════════╪═════════════╡
│ 41.9136  ┆ 42.0        │
│ 219.582  ┆ 220.0       │
│ 6.8714   ┆ 7.0         │
│ -383.031 ┆ -383.0      │
│ 2.5164   ┆ 3.0         │
└──────────┴─────────────┘

In [8]:
path = './Files/Sample_Superstore.csv'
pl.read_csv(
    path
    ).select('Profit').with_columns(
    RoundProfit=pl.col('Profit').round(0)).head()
#select returns subset but withcolumn returns alll colums

shape: (5, 2)
┌──────────┬─────────────┐
│ Profit   ┆ RoundProfit │
│ ---      ┆ ---         │
│ f64      ┆ f64         │
╞══════════╪═════════════╡
│ 41.9136  ┆ 42.0        │
│ 219.582  ┆ 220.0       │
│ 6.8714   ┆ 7.0         │
│ -383.031 ┆ -383.0      │
│ 2.5164   ┆ 3.0         │
└──────────┴─────────────┘

In [10]:
pl.read_csv(
    path
    ).select('Profit').with_columns(
    (pl.col('Profit') * 2).alias('doubleProfit')).head()

shape: (5, 2)
┌──────────┬──────────────┐
│ Profit   ┆ doubleProfit │
│ ---      ┆ ---          │
│ f64      ┆ f64          │
╞══════════╪══════════════╡
│ 41.9136  ┆ 83.8272      │
│ 219.582  ┆ 439.164      │
│ 6.8714   ┆ 13.7428      │
│ -383.031 ┆ -766.062     │
│ 2.5164   ┆ 5.0328       │
└──────────┴──────────────┘

In [15]:
st.select('Profit', 'Discount').with_columns(
    (pl.col('Profit') + pl.col('Discount')).alias('ProfitplusDiscount')).head()

shape: (5, 3)
┌──────────┬──────────┬────────────────────┐
│ Profit   ┆ Discount ┆ ProfitplusDiscount │
│ ---      ┆ ---      ┆ ---                │
│ f64      ┆ f64      ┆ f64                │
╞══════════╪══════════╪════════════════════╡
│ 41.9136  ┆ 0.0      ┆ 41.9136            │
│ 219.582  ┆ 0.0      ┆ 219.582            │
│ 6.8714   ┆ 0.0      ┆ 6.8714             │
│ -383.031 ┆ 0.45     ┆ -382.581           │
│ 2.5164   ┆ 0.2      ┆ 2.7164             │
└──────────┴──────────┴────────────────────┘

In [16]:
st.select('Profit', 'Discount').with_columns(
    pl.col('Profit').add(pl.col('Discount')).alias('ProfitplusDiscount')).head()

shape: (5, 3)
┌──────────┬──────────┬────────────────────┐
│ Profit   ┆ Discount ┆ ProfitplusDiscount │
│ ---      ┆ ---      ┆ ---                │
│ f64      ┆ f64      ┆ f64                │
╞══════════╪══════════╪════════════════════╡
│ 41.9136  ┆ 0.0      ┆ 41.9136            │
│ 219.582  ┆ 0.0      ┆ 219.582            │
│ 6.8714   ┆ 0.0      ┆ 6.8714             │
│ -383.031 ┆ 0.45     ┆ -382.581           │
│ 2.5164   ┆ 0.2      ┆ 2.7164             │
└──────────┴──────────┴────────────────────┘

In [17]:
#Constant val
st.with_columns(pl.lit('yes').alias('Aboard')).select('Customer_Name', 'Aboard').head()

shape: (5, 2)
┌─────────────────┬────────┐
│ Customer_Name   ┆ Aboard │
│ ---             ┆ ---    │
│ str             ┆ str    │
╞═════════════════╪════════╡
│ Claire Gute     ┆ yes    │
│ Claire Gute     ┆ yes    │
│ Darrin Van Huff ┆ yes    │
│ Sean O'Donnell  ┆ yes    │
│ Sean O'Donnell  ┆ yes    │
└─────────────────┴────────┘

In [18]:
st.select('Profit', 'Discount').with_columns(
    pl.col('Profit').round(0),
    pl.col('Discount').round(0)
).head() #pl.col('Discount', 'Profit').round(0)

shape: (5, 2)
┌────────┬──────────┐
│ Profit ┆ Discount │
│ ---    ┆ ---      │
│ f64    ┆ f64      │
╞════════╪══════════╡
│ 42.0   ┆ 0.0      │
│ 220.0  ┆ 0.0      │
│ 7.0    ┆ 0.0      │
│ -383.0 ┆ 0.0      │
│ 3.0    ┆ 0.0      │
└────────┴──────────┘

In [19]:
st.select('Profit', 'Discount', 'Sales').with_columns(
    pl.col(pl.Float64).round(0),
).head() #cs.float().round(0)

shape: (5, 3)
┌────────┬──────────┬───────┐
│ Profit ┆ Discount ┆ Sales │
│ ---    ┆ ---      ┆ ---   │
│ f64    ┆ f64      ┆ f64   │
╞════════╪══════════╪═══════╡
│ 42.0   ┆ 0.0      ┆ 262.0 │
│ 220.0  ┆ 0.0      ┆ 732.0 │
│ 7.0    ┆ 0.0      ┆ 15.0  │
│ -383.0 ┆ 0.0      ┆ 958.0 │
│ 3.0    ┆ 0.0      ┆ 22.0  │
└────────┴──────────┴───────┘

In [20]:
st.with_columns(
    pl.col('Profit').round(0).alias('Rnd_Profit'),
    pl.col('Discount').round(0).alias('Rnd_Discount')
).select('Profit', 'Discount', 'Rnd_Profit', 'Rnd_Discount').head()

shape: (5, 4)
┌──────────┬──────────┬────────────┬──────────────┐
│ Profit   ┆ Discount ┆ Rnd_Profit ┆ Rnd_Discount │
│ ---      ┆ ---      ┆ ---        ┆ ---          │
│ f64      ┆ f64      ┆ f64        ┆ f64          │
╞══════════╪══════════╪════════════╪══════════════╡
│ 41.9136  ┆ 0.0      ┆ 42.0       ┆ 0.0          │
│ 219.582  ┆ 0.0      ┆ 220.0      ┆ 0.0          │
│ 6.8714   ┆ 0.0      ┆ 7.0        ┆ 0.0          │
│ -383.031 ┆ 0.45     ┆ -383.0     ┆ 0.0          │
│ 2.5164   ┆ 0.2      ┆ 3.0        ┆ 0.0          │
└──────────┴──────────┴────────────┴──────────────┘

In [21]:
st.with_columns(
    Rnd_Profit=pl.col('Profit').round(0),
    Rnd_Discount=pl.col('Discount').round(0)
).select('Profit', 'Discount', 'Rnd_Profit', 'Rnd_Discount').head()

shape: (5, 4)
┌──────────┬──────────┬────────────┬──────────────┐
│ Profit   ┆ Discount ┆ Rnd_Profit ┆ Rnd_Discount │
│ ---      ┆ ---      ┆ ---        ┆ ---          │
│ f64      ┆ f64      ┆ f64        ┆ f64          │
╞══════════╪══════════╪════════════╪══════════════╡
│ 41.9136  ┆ 0.0      ┆ 42.0       ┆ 0.0          │
│ 219.582  ┆ 0.0      ┆ 220.0      ┆ 0.0          │
│ 6.8714   ┆ 0.0      ┆ 7.0        ┆ 0.0          │
│ -383.031 ┆ 0.45     ┆ -383.0     ┆ 0.0          │
│ 2.5164   ┆ 0.2      ┆ 3.0        ┆ 0.0          │
└──────────┴──────────┴────────────┴──────────────┘

In [23]:
st.with_columns(
  pl.col(pl.Float64).round(0).name.suffix('_round'),
).select('Profit', 'Discount', 'Profit_round', 'Discount_round').head()

shape: (5, 4)
┌──────────┬──────────┬──────────────┬────────────────┐
│ Profit   ┆ Discount ┆ Profit_round ┆ Discount_round │
│ ---      ┆ ---      ┆ ---          ┆ ---            │
│ f64      ┆ f64      ┆ f64          ┆ f64            │
╞══════════╪══════════╪══════════════╪════════════════╡
│ 41.9136  ┆ 0.0      ┆ 42.0         ┆ 0.0            │
│ 219.582  ┆ 0.0      ┆ 220.0        ┆ 0.0            │
│ 6.8714   ┆ 0.0      ┆ 7.0          ┆ 0.0            │
│ -383.031 ┆ 0.45     ┆ -383.0       ┆ 0.0            │
│ 2.5164   ┆ 0.2      ┆ 3.0          ┆ 0.0            │
└──────────┴──────────┴──────────────┴────────────────┘

In [24]:
df = pl.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [25, 30, 35, 40],
    "salary": [50000, 60000, 70000, 80000]
})
 
print("Original DataFrame:")
print(df)

Original DataFrame:
shape: (4, 3)
┌─────────┬─────┬────────┐
│ name    ┆ age ┆ salary │
│ ---     ┆ --- ┆ ---    │
│ str     ┆ i64 ┆ i64    │
╞═════════╪═════╪════════╡
│ Alice   ┆ 25  ┆ 50000  │
│ Bob     ┆ 30  ┆ 60000  │
│ Charlie ┆ 35  ┆ 70000  │
│ David   ┆ 40  ┆ 80000  │
└─────────┴─────┴────────┘

In [27]:
df = df.with_columns(
    pl.when(pl.col("age") > 30)
      .then(pl.lit("Senior"))
      .otherwise(pl.lit("Junior"))
      .alias("category")
)
 
print("\nDataFrame with Conditional Column:")
print(df)

DataFrame with Conditional Column:
shape: (4, 4)
┌─────────┬─────┬────────┬──────────┐
│ name    ┆ age ┆ salary ┆ category │
│ ---     ┆ --- ┆ ---    ┆ ---      │
│ str     ┆ i64 ┆ i64    ┆ str      │
╞═════════╪═════╪════════╪══════════╡
│ Alice   ┆ 25  ┆ 50000  ┆ Junior   │
│ Bob     ┆ 30  ┆ 60000  ┆ Junior   │
│ Charlie ┆ 35  ┆ 70000  ┆ Senior   │
│ David   ┆ 40  ┆ 80000  ┆ Senior   │
└─────────┴─────┴────────┴──────────┘

In [30]:
#rename
st.rename({'Order_ID': 'ID'}).head()

shape: (5, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ ID            ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ CA-2016-15215 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [31]:
#DELETE
st.drop(['Order_ID', 'Postal_Code']).head()

shape: (5, 19)
┌────────┬────────────┬────────────┬───────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_Date ┆ Ship_Date  ┆ Ship_Mode     ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---        ┆ ---        ┆ ---           ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str        ┆ str        ┆ str           ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪════════════╪════════════╪═══════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null       ┆ 11-11-2016 ┆ Second Class  ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ 08-11-2016 ┆ 11-11-2016 ┆ Second Class  ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│ 3      ┆ 12-06-2016 ┆ null       ┆ null          ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│ 4      ┆ 11-10-2015 ┆ null       ┆ Standard      ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│        ┆            ┆            ┆ Class         ┆   ┆          ┆          ┆          ┆          │
│ 5      ┆ 11-10-2015 ┆ 18-10-2015 ┆ Standard      ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆            ┆            ┆ Class         ┆   ┆          ┆          ┆          ┆          │
└────────┴────────────┴────────────┴───────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [33]:
st.select(sorted(st.columns)).head()

shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Category  ┆ City      ┆ Country   ┆ Customer_ ┆ … ┆ Ship_Date ┆ Ship_Mode ┆ State     ┆ Sub_Cate │
│ ---       ┆ ---       ┆ ---       ┆ ID        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ gory     │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Furniture ┆ Henderson ┆ United    ┆ CG-12520  ┆ … ┆ 11-11-201 ┆ Second    ┆ Kentucky  ┆ Bookcase │
│           ┆           ┆ States    ┆           ┆   ┆ 6         ┆ Class     ┆           ┆ s        │
│ Furniture ┆ Henderson ┆ United    ┆ CG-12520  ┆ … ┆ 11-11-201 ┆ Second    ┆ Kentucky  ┆ Chairs   │
│           ┆           ┆ States    ┆           ┆   ┆ 6         ┆ Class     ┆           ┆          │
│ Office    ┆ Los       ┆ null      ┆ DV-13045  ┆ … ┆ null      ┆ null      ┆ Californi ┆ Labels   │
│ Supplies  ┆ Angeles   ┆           ┆           ┆   ┆           ┆           ┆ a         ┆          │
│ Furniture ┆ Fort Laud ┆ United    ┆ SO-20335  ┆ … ┆ null      ┆ Standard  ┆ Florida   ┆ Tables   │
│           ┆ erdale    ┆ States    ┆           ┆   ┆           ┆ Class     ┆           ┆          │
│ Office    ┆ null      ┆ United    ┆ SO-20335  ┆ … ┆ 18-10-201 ┆ Standard  ┆ Florida   ┆ Storage  │
│ Supplies  ┆           ┆ States    ┆           ┆   ┆ 5         ┆ Class     ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [34]:
#Type change
st.cast({'Row_ID': pl.Utf8}).head()

shape: (5, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ CA-2016-15215 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [35]:
st.cast(pl.Utf8).head()

shape: (5, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ str           ┆ str        ┆ str        ┆   ┆ str      ┆ str      ┆ str      ┆ str      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ CA-2016-15215 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [37]:
import polars.selectors as cs
st.cast({cs.numeric(): pl.Utf8}).head()

shape: (5, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ str           ┆ str        ┆ str        ┆   ┆ str      ┆ str      ┆ str      ┆ str      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ CA-2016-15215 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

# Iterating
**Avoid iterating apply tranformations directly**
*df = df.with_columns(
    (df["score"] + 5).alias("adjusted_score")
)*

In [40]:
Profits = [pft for pft in st['Profit']]
Profits[:3]

[41.9136, 219.582, 6.8714]

In [44]:
c_profit = [(row[3], row[5]) for row in st.rows()]
c_profit[:3]

[('11-11-2016', 'CG-12520'), ('11-11-2016', 'CG-12520'), (None, 'DV-13045')]

In [52]:
c_profit = [(row[3], row[5]) for row in st.iter_rows()]
c_profit[:3]

[('11-11-2016', 'CG-12520'), ('11-11-2016', 'CG-12520'), (None, 'DV-13045')]

In [48]:
#rows() and iter_rows()  rows returns full data while iter_rows yields when needed as tuple
c_profit = [(row['Customer_Name'], row['Profit']) for row in st.rows(named=True)]
#st.rows(named=True)#Returns dict
c_profit[:3]

[('Claire Gute', 41.9136),
 ('Claire Gute', 219.582),
 ('Darrin Van Huff', 6.8714)]