In [2]:
import polars as pl

csv = pl.read_csv('./Files/Sample_Superstore.csv')

In [3]:
csv.mean() #Dataframe

shape: (1, 21)
┌────────┬──────────┬────────────┬───────────┬───┬────────────┬──────────┬──────────┬───────────┐
│ Row_ID ┆ Order_ID ┆ Order_Date ┆ Ship_Date ┆ … ┆ Sales      ┆ Quantity ┆ Discount ┆ Profit    │
│ ---    ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---        ┆ ---      ┆ ---      ┆ ---       │
│ f64    ┆ str      ┆ str        ┆ str       ┆   ┆ f64        ┆ f64      ┆ f64      ┆ f64       │
╞════════╪══════════╪════════════╪═══════════╪═══╪════════════╪══════════╪══════════╪═══════════╡
│ 4997.5 ┆ null     ┆ null       ┆ null      ┆ … ┆ 229.858001 ┆ 3.789574 ┆ 0.156203 ┆ 28.656896 │
└────────┴──────────┴────────────┴───────────┴───┴────────────┴──────────┴──────────┴───────────┘

In [4]:
csv.max()

shape: (1, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 9994   ┆ US-2017-16955 ┆ 31-12-2016 ┆ 31-12-2017 ┆ … ┆ 22638.48 ┆ 14       ┆ 0.8      ┆ 8399.976 │
│        ┆ 1             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [5]:
csv.min()

shape: (1, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬───────┬──────────┬──────────┬───────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales ┆ Quantity ┆ Discount ┆ Profit    │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---   ┆ ---      ┆ ---      ┆ ---       │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64   ┆ i64      ┆ f64      ┆ f64       │
╞════════╪════════════════╪════════════╪════════════╪═══╪═══════╪══════════╪══════════╪═══════════╡
│ 1      ┆ CA-2014-100006 ┆ 01-01-2017 ┆ 01-01-2015 ┆ … ┆ 0.444 ┆ 1        ┆ 0.0      ┆ -6599.978 │
└────────┴────────────────┴────────────┴────────────┴───┴───────┴──────────┴──────────┴───────────┘

In [6]:
csv.count()

shape: (1, 21)
┌────────┬──────────┬────────────┬───────────┬───┬───────┬──────────┬──────────┬────────┐
│ Row_ID ┆ Order_ID ┆ Order_Date ┆ Ship_Date ┆ … ┆ Sales ┆ Quantity ┆ Discount ┆ Profit │
│ ---    ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---   ┆ ---      ┆ ---      ┆ ---    │
│ u32    ┆ u32      ┆ u32        ┆ u32       ┆   ┆ u32   ┆ u32      ┆ u32      ┆ u32    │
╞════════╪══════════╪════════════╪═══════════╪═══╪═══════╪══════════╪══════════╪════════╡
│ 9994   ┆ 9992     ┆ 9993       ┆ 9992      ┆ … ┆ 9994  ┆ 9994     ┆ 9994     ┆ 9994   │
└────────┴──────────┴────────────┴───────────┴───┴───────┴──────────┴──────────┴────────┘

In [7]:
csv.sum()

shape: (1, 21)
┌──────────┬──────────┬────────────┬───────────┬───┬──────────┬──────────┬──────────┬─────────────┐
│ Row_ID   ┆ Order_ID ┆ Order_Date ┆ Ship_Date ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit      │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---         │
│ i64      ┆ str      ┆ str        ┆ str       ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64         │
╞══════════╪══════════╪════════════╪═══════════╪═══╪══════════╪══════════╪══════════╪═════════════╡
│ 49945015 ┆ null     ┆ null       ┆ null      ┆ … ┆ 2.2972e6 ┆ 37873    ┆ 1561.09  ┆ 286397.0217 │
└──────────┴──────────┴────────────┴───────────┴───┴──────────┴──────────┴──────────┴─────────────┘

In [8]:
csv.shape

(9994, 21)

In [9]:
csv.select(pl.col('Profit')).mean()

shape: (1, 1)
┌───────────┐
│ Profit    │
│ ---       │
│ f64       │
╞═══════════╡
│ 28.656896 │
└───────────┘

In [10]:
csv.select(pl.col('Profit')).max()

shape: (1, 1)
┌──────────┐
│ Profit   │
│ ---      │
│ f64      │
╞══════════╡
│ 8399.976 │
└──────────┘

In [12]:
type(csv.select(csv['Profit']).mean())

polars.dataframe.frame.DataFrame

In [13]:
print(csv.select(pl.col('Profit')).min())
print(csv.select(pl.col('Profit')).count())
print(csv.select(pl.col('Profit')).sum())

shape: (1, 1)
┌───────────┐
│ Profit    │
│ ---       │
│ f64       │
╞═══════════╡
│ -6599.978 │
└───────────┘
shape: (1, 1)
┌────────┐
│ Profit │
│ ---    │
│ u32    │
╞════════╡
│ 9994   │
└────────┘
shape: (1, 1)
┌─────────────┐
│ Profit      │
│ ---         │
│ f64         │
╞═════════════╡
│ 286397.0217 │
└─────────────┘

In [14]:
csv.unique(subset=['Customer_Name']).select('Customer_Name')

shape: (793, 1)
┌─────────────────┐
│ Customer_Name   │
│ ---             │
│ str             │
╞═════════════════╡
│ Bradley Talbott │
│ Ed Braxton      │
│ Corey Catlett   │
│ Dorothy Wardle  │
│ Justin Ellison  │
│ …               │
│ Harold Engle    │
│ Liz MacKendrick │
│ Joel Eaton      │
│ Thea Hendricks  │
│ Erin Ashbrook   │
└─────────────────┘

In [15]:
csv.select(pl.col('Customer_Name')).unique()

shape: (793, 1)
┌────────────────────┐
│ Customer_Name      │
│ ---                │
│ str                │
╞════════════════════╡
│ Russell D'Ascenzo  │
│ Mary Zewe          │
│ Natalie DeCherney  │
│ Jas O'Carroll      │
│ Michael Nguyen     │
│ …                  │
│ Ralph Ritter       │
│ Christopher Conant │
│ Ken Dana           │
│ John Lucas         │
│ Sally Matthias     │
└────────────────────┘

In [16]:
csv.unique(subset=['Customer_Name', 'Profit']).select(pl.col('Customer_Name','Profit'))

shape: (9_977, 2)
┌───────────────────┬──────────┐
│ Customer_Name     ┆ Profit   │
│ ---               ┆ ---      │
│ str               ┆ f64      │
╞═══════════════════╪══════════╡
│ Laura Armstrong   ┆ 52.1262  │
│ Thomas Thornton   ┆ 10.8588  │
│ Annie Thurman     ┆ 41.68    │
│ Irene Maddox      ┆ -248.166 │
│ Deborah Brumfield ┆ -11.0208 │
│ …                 ┆ …        │
│ Rick Duston       ┆ 0.84     │
│ Annie Zypern      ┆ 50.3658  │
│ Sam Zeldin        ┆ 6.8768   │
│ Barry Pond        ┆ 2.502    │
│ John Lee          ┆ 12.0764  │
└───────────────────┴──────────┘

In [17]:
csv.select(pl.col('Customer_Name','Profit')).unique()

shape: (9_977, 2)
┌──────────────────────┬──────────┐
│ Customer_Name        ┆ Profit   │
│ ---                  ┆ ---      │
│ str                  ┆ f64      │
╞══════════════════════╪══════════╡
│ Russell Applegate    ┆ 24.47    │
│ Ryan Akin            ┆ 4.4604   │
│ Noel Staavos         ┆ 4.3836   │
│ Mitch Webber         ┆ 0.5      │
│ David Bremer         ┆ 14.2992  │
│ …                    ┆ …        │
│ Justin Ritter        ┆ 61.3824  │
│ Eugene Barchas       ┆ 0.564    │
│ Christine Sundaresam ┆ 7.4872   │
│ Richard Bierner      ┆ -85.2384 │
│ Darren Powers        ┆ 5.5512   │
└──────────────────────┴──────────┘

In [19]:
csv[[2,3]]

shape: (2, 21)
┌────────┬────────────────┬────────────┬───────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---            ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str            ┆ str        ┆ str       ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪════════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 3      ┆ CA-2016-138688 ┆ 12-06-2016 ┆ null      ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│ 4      ┆ null           ┆ 11-10-2015 ┆ null      ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
└────────┴────────────────┴────────────┴───────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [20]:
csv[:2]

shape: (2, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 1      ┆ null           ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96 ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

In [21]:
csv[range(2, 8)]

shape: (6, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 6      ┆ CA-2014-11581 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 48.86    ┆ 7        ┆ 0.0      ┆ 14.1694  │
│        ┆ 2             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 7      ┆ CA-2014-11581 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 7.28     ┆ 4        ┆ 0.0      ┆ 1.9656   │
│        ┆ 2             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 8      ┆ CA-2014-11581 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 907.152  ┆ 6        ┆ 0.2      ┆ 90.7152  │
│        ┆ 2             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [22]:
import numpy as np
csv[np.arange(0, 3)]

shape: (3, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 1      ┆ null           ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96 ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 3      ┆ CA-2016-138688 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62  ┆ 2        ┆ 0.0      ┆ 6.8714  │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

In [23]:
#Integer columns
csv.filter(pl.col('Profit') > 1000).select('Row_ID', 'Customer_Name', 'Profit').head(2)

shape: (2, 3)
┌────────┬─────────────────┬───────────┐
│ Row_ID ┆ Customer_Name   ┆ Profit    │
│ ---    ┆ ---             ┆ ---       │
│ i64    ┆ str             ┆ f64       │
╞════════╪═════════════════╪═══════════╡
│ 319    ┆ Nathan Mautz    ┆ 1995.99   │
│ 354    ┆ Adam Bellavance ┆ 1415.4296 │
└────────┴─────────────────┴───────────┘

In [24]:
csv.filter(pl.col('Profit') <= 1000).select('Row_ID', 'Customer_Name', 'Profit').head(2)

shape: (2, 3)
┌────────┬───────────────┬─────────┐
│ Row_ID ┆ Customer_Name ┆ Profit  │
│ ---    ┆ ---           ┆ ---     │
│ i64    ┆ str           ┆ f64     │
╞════════╪═══════════════╪═════════╡
│ 1      ┆ Claire Gute   ┆ 41.9136 │
│ 2      ┆ Claire Gute   ┆ 219.582 │
└────────┴───────────────┴─────────┘

In [26]:
csv.filter((pl.col('Profit') <= 500) & (pl.col('Quantity') == 5)).select(
    'Row_ID', 'Customer_Name', 'Profit'
).head(2)

shape: (2, 3)
┌────────┬─────────────────┬──────────┐
│ Row_ID ┆ Customer_Name   ┆ Profit   │
│ ---    ┆ ---             ┆ ---      │
│ i64    ┆ str             ┆ f64      │
╞════════╪═════════════════╪══════════╡
│ 4      ┆ Sean O'Donnell  ┆ -383.031 │
│ 10     ┆ Brosina Hoffman ┆ 34.47    │
└────────┴─────────────────┴──────────┘

In [29]:
csv.filter(pl.col('Profit') <= 1000, pl.col('Profit') >= 5).select(
    'Row_ID', 'Customer_Name', 'Profit'
).head(10) #AND

shape: (10, 3)
┌────────┬─────────────────┬─────────┐
│ Row_ID ┆ Customer_Name   ┆ Profit  │
│ ---    ┆ ---             ┆ ---     │
│ i64    ┆ str             ┆ f64     │
╞════════╪═════════════════╪═════════╡
│ 1      ┆ Claire Gute     ┆ 41.9136 │
│ 2      ┆ Claire Gute     ┆ 219.582 │
│ 3      ┆ Darrin Van Huff ┆ 6.8714  │
│ 6      ┆ Brosina Hoffman ┆ 14.1694 │
│ 8      ┆ Brosina Hoffman ┆ 90.7152 │
│ 9      ┆ Brosina Hoffman ┆ 5.7825  │
│ 10     ┆ Brosina Hoffman ┆ 34.47   │
│ 11     ┆ Brosina Hoffman ┆ 85.3092 │
│ 12     ┆ Brosina Hoffman ┆ 68.3568 │
│ 13     ┆ Andrew Allen    ┆ 5.4432  │
└────────┴─────────────────┴─────────┘

In [31]:
csv.filter(pl.col('Quantity').is_in([2, 3])).select(
    'Row_ID', 'Customer_Name', 'Quantity'
).head(10)

shape: (10, 3)
┌────────┬────────────────────┬──────────┐
│ Row_ID ┆ Customer_Name      ┆ Quantity │
│ ---    ┆ ---                ┆ ---      │
│ i64    ┆ str                ┆ i64      │
╞════════╪════════════════════╪══════════╡
│ 1      ┆ Claire Gute        ┆ 2        │
│ 2      ┆ Claire Gute        ┆ 3        │
│ 3      ┆ Darrin Van Huff    ┆ 2        │
│ 5      ┆ Sean O'Donnell     ┆ 2        │
│ 9      ┆ Brosina Hoffman    ┆ 3        │
│ 13     ┆ Andrew Allen       ┆ 3        │
│ 14     ┆ Irene Maddox       ┆ 3        │
│ 16     ┆ Harold Pawlan      ┆ 3        │
│ 18     ┆ Alejandro Grove    ┆ 2        │
│ 19     ┆ Zuschuss Donatelli ┆ 2        │
└────────┴────────────────────┴──────────┘

In [35]:
csv.filter(((pl.col('Profit') <= 500) & (pl.col('Quantity') == 5)) | (pl.col('City') == 'Los Angeles')).select(
    'Row_ID', 'Customer_Name', 'Profit', 'City'
).head(2)

shape: (2, 4)
┌────────┬─────────────────┬──────────┬─────────────────┐
│ Row_ID ┆ Customer_Name   ┆ Profit   ┆ City            │
│ ---    ┆ ---             ┆ ---      ┆ ---             │
│ i64    ┆ str             ┆ f64      ┆ str             │
╞════════╪═════════════════╪══════════╪═════════════════╡
│ 3      ┆ Darrin Van Huff ┆ 6.8714   ┆ Los Angeles     │
│ 4      ┆ Sean O'Donnell  ┆ -383.031 ┆ Fort Lauderdale │
└────────┴─────────────────┴──────────┴─────────────────┘

In [50]:
csv.filter(pl.col('Profit').is_between(1000, 2000)).select(
    'Row_ID', 'Customer_Name', 'Profit'
)

shape: (27, 3)
┌────────┬──────────────────┬───────────┐
│ Row_ID ┆ Customer_Name    ┆ Profit    │
│ ---    ┆ ---              ┆ ---       │
│ i64    ┆ str              ┆ f64       │
╞════════╪══════════════════╪═══════════╡
│ 319    ┆ Nathan Mautz     ┆ 1995.99   │
│ 354    ┆ Adam Bellavance  ┆ 1415.4296 │
│ 516    ┆ Alan Dominguez   ┆ 1379.977  │
│ 995    ┆ Mitch Willingham ┆ 1276.4871 │
│ 1455   ┆ Mark Cousins     ┆ 1459.2    │
│ …      ┆ …                ┆ …         │
│ 7915   ┆ Steven Roelle    ┆ 1668.205  │
│ 8750   ┆ Lena Creighton   ┆ 1143.891  │
│ 8859   ┆ Jane Waco        ┆ 1906.485  │
│ 9271   ┆ Pete Kriz        ┆ 1453.1238 │
│ 9742   ┆ Quincy Jones     ┆ 1013.127  │
└────────┴──────────────────┴───────────┘

In [39]:
# String
csv.filter(pl.col('City') == 'Henderson').select(
    'Row_ID', 'Customer_Name', 'City'
).head(10) #> < >=

shape: (10, 3)
┌────────┬────────────────┬───────────┐
│ Row_ID ┆ Customer_Name  ┆ City      │
│ ---    ┆ ---            ┆ ---       │
│ i64    ┆ str            ┆ str       │
╞════════╪════════════════╪═══════════╡
│ 1      ┆ Claire Gute    ┆ Henderson │
│ 2      ┆ Claire Gute    ┆ Henderson │
│ 539    ┆ Darren Koutras ┆ Henderson │
│ 540    ┆ Darren Koutras ┆ Henderson │
│ 997    ┆ Rob Dowd       ┆ Henderson │
│ 998    ┆ Rob Dowd       ┆ Henderson │
│ 999    ┆ Rob Dowd       ┆ Henderson │
│ 1000   ┆ Rob Dowd       ┆ Henderson │
│ 1867   ┆ Adam Hart      ┆ Henderson │
│ 2322   ┆ Karen Carlisle ┆ Henderson │
└────────┴────────────────┴───────────┘

In [40]:
csv.filter(pl.col('City').is_in(['Los Angeles', 'Henderson'])).select(
    'Row_ID', 'Customer_Name', 'City'
).head(10)

shape: (10, 3)
┌────────┬─────────────────┬─────────────┐
│ Row_ID ┆ Customer_Name   ┆ City        │
│ ---    ┆ ---             ┆ ---         │
│ i64    ┆ str             ┆ str         │
╞════════╪═════════════════╪═════════════╡
│ 1      ┆ Claire Gute     ┆ Henderson   │
│ 2      ┆ Claire Gute     ┆ Henderson   │
│ 3      ┆ Darrin Van Huff ┆ Los Angeles │
│ 6      ┆ Brosina Hoffman ┆ Los Angeles │
│ 7      ┆ Brosina Hoffman ┆ Los Angeles │
│ 8      ┆ Brosina Hoffman ┆ Los Angeles │
│ 9      ┆ Brosina Hoffman ┆ Los Angeles │
│ 10     ┆ Brosina Hoffman ┆ Los Angeles │
│ 11     ┆ Brosina Hoffman ┆ Los Angeles │
│ 12     ┆ Brosina Hoffman ┆ Los Angeles │
└────────┴─────────────────┴─────────────┘

In [41]:
csv.filter(pl.col('Customer_Name').str.contains('Hale')).select(
    'Row_ID', 'Customer_Name', 'City'
).head(10)  # &  |

shape: (3, 3)
┌────────┬───────────────┬────────────┐
│ Row_ID ┆ Customer_Name ┆ City       │
│ ---    ┆ ---           ┆ ---        │
│ i64    ┆ str           ┆ str        │
╞════════╪═══════════════╪════════════╡
│ 36     ┆ Gene Hale     ┆ Richardson │
│ 37     ┆ Gene Hale     ┆ Richardson │
│ 8134   ┆ Gene Hale     ┆ Dallas     │
└────────┴───────────────┴────────────┘

In [42]:
#Date
df = pl.read_csv('./Files/Sample_Superstore.csv', try_parse_dates=True)

In [43]:
df.head()

shape: (5, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ date       ┆ date       ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 2016-11-11 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ CA-2016-15215 ┆ 2016-11-08 ┆ 2016-11-11 ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 3      ┆ CA-2016-13868 ┆ 2016-06-12 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 2015-10-11 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 2015-10-11 ┆ 2015-10-18 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [46]:
from datetime import datetime
df.filter(pl.col('Order_Date') == datetime(2016, 11, 8)).head()  #!=

shape: (1, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ date       ┆ date       ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ 2      ┆ CA-2016-152156 ┆ 2016-11-08 ┆ 2016-11-11 ┆ … ┆ 731.94 ┆ 3        ┆ 0.0      ┆ 219.582 │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴─────────┘

In [47]:
from datetime import datetime
df.filter(pl.col('Order_Date').is_between(datetime(2016, 11, 8), datetime(2017, 11, 8))).head()

shape: (5, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬─────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales   ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---     ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str            ┆ date       ┆ date       ┆   ┆ f64     ┆ i64      ┆ f64      ┆ f64      │
╞════════╪════════════════╪════════════╪════════════╪═══╪═════════╪══════════╪══════════╪══════════╡
│ 2      ┆ CA-2016-152156 ┆ 2016-11-08 ┆ 2016-11-11 ┆ … ┆ 731.94  ┆ 3        ┆ 0.0      ┆ 219.582  │
│ 13     ┆ CA-2017-114412 ┆ 2017-04-15 ┆ 2017-04-20 ┆ … ┆ 15.552  ┆ 3        ┆ 0.2      ┆ 5.4432   │
│ 14     ┆ CA-2016-161389 ┆ 2016-12-05 ┆ 2016-12-10 ┆ … ┆ 407.976 ┆ 3        ┆ 0.2      ┆ 132.5922 │
│ 22     ┆ CA-2016-137330 ┆ 2016-12-09 ┆ 2016-12-13 ┆ … ┆ 19.46   ┆ 7        ┆ 0.0      ┆ 5.0596   │
│ 23     ┆ CA-2016-137330 ┆ 2016-12-09 ┆ 2016-12-13 ┆ … ┆ 60.34   ┆ 7        ┆ 0.0      ┆ 15.6884  │
└────────┴────────────────┴────────────┴────────────┴───┴─────────┴──────────┴──────────┴──────────┘

In [49]:
#Boolean
#df.filter(pl.col('Is_Return') == True).select('Profit', 'Is_Return') ~ for not
df.columns #pl.col(boolcolumn).not_()

['Row_ID',
 'Order_ID',
 'Order_Date',
 'Ship_Date',
 'Ship_Mode',
 'Customer_ID',
 'Customer_Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal_Code',
 'Region',
 'Product_ID',
 'Category',
 'Sub_Category',
 'Product_Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

```
df_filtered = df_main.filter(df_main["id"].is_in(df_filter["id"]))
 
print("\nFiltered DataFrame:")
print(df_filtered)
python
df_filtered = df_main.join(df_filter, on="id", how="inner")
 
print("\nFiltered DataFrame (using join):")
print(df_filtered)
```