In [1]:
import polars as pl
import polars.selectors as cs

path = './Files/Sample_Superstore.csv'
df = pl.read_csv(path)

# Finding

In [2]:
#Nan, None or Null is used depending on datatype
df.null_count()

shape: (1, 21)
┌────────┬──────────┬────────────┬───────────┬───┬───────┬──────────┬──────────┬────────┐
│ Row_ID ┆ Order_ID ┆ Order_Date ┆ Ship_Date ┆ … ┆ Sales ┆ Quantity ┆ Discount ┆ Profit │
│ ---    ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---   ┆ ---      ┆ ---      ┆ ---    │
│ u32    ┆ u32      ┆ u32        ┆ u32       ┆   ┆ u32   ┆ u32      ┆ u32      ┆ u32    │
╞════════╪══════════╪════════════╪═══════════╪═══╪═══════╪══════════╪══════════╪════════╡
│ 0      ┆ 2        ┆ 1          ┆ 2         ┆ … ┆ 0     ┆ 0        ┆ 0        ┆ 0      │
└────────┴──────────┴────────────┴───────────┴───┴───────┴──────────┴──────────┴────────┘

In [3]:
df.dtypes

[Int64,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 String,
 Int64,
 String,
 String,
 String,
 String,
 String,
 Float64,
 Int64,
 Float64,
 Float64]

In [4]:
df.select(
    pl.col('Customer_Name'),
    pl.col('Category').is_null().alias('Category_is_null'),
    pl.col('Region').is_null().alias('Region_is_null'),
).head()

shape: (5, 3)
┌─────────────────┬──────────────────┬────────────────┐
│ Customer_Name   ┆ Category_is_null ┆ Region_is_null │
│ ---             ┆ ---              ┆ ---            │
│ str             ┆ bool             ┆ bool           │
╞═════════════════╪══════════════════╪════════════════╡
│ Claire Gute     ┆ false            ┆ false          │
│ Claire Gute     ┆ false            ┆ false          │
│ Darrin Van Huff ┆ false            ┆ false          │
│ Sean O'Donnell  ┆ false            ┆ false          │
│ Sean O'Donnell  ┆ false            ┆ false          │
└─────────────────┴──────────────────┴────────────────┘

In [9]:
df.filter(pl.col('Category').is_null()).select('Category', 'Profit', 'Customer_Name').head()

shape: (0, 3)
┌──────────┬────────┬───────────────┐
│ Category ┆ Profit ┆ Customer_Name │
│ ---      ┆ ---    ┆ ---           │
│ str      ┆ f64    ┆ str           │
╞══════════╪════════╪═══════════════╡
└──────────┴────────┴───────────────┘

In [10]:
df.filter(pl.any_horizontal(pl.all().is_null())).head() #filter by multiple columns with null

shape: (5, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 8      ┆ CA-2014-11581 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 907.152  ┆ 6        ┆ 0.2      ┆ 90.7152  │
│        ┆ 2             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [11]:
df.drop_nulls(subset=['Ship_Date']) #Drop all rows with null ship dates

shape: (9_992, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬─────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales   ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---     ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64     ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪═════════╪══════════╪══════════╪═════════╡
│ 1      ┆ null           ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96  ┆ 2        ┆ 0.0      ┆ 41.9136 │
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94  ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 5      ┆ US-2015-108966 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368  ┆ 2        ┆ 0.2      ┆ 2.5164  │
│ 6      ┆ CA-2014-115812 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 48.86   ┆ 7        ┆ 0.0      ┆ 14.1694 │
│ 7      ┆ CA-2014-115812 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 7.28    ┆ 4        ┆ 0.0      ┆ 1.9656  │
│ …      ┆ …              ┆ …          ┆ …          ┆ … ┆ …       ┆ …        ┆ …        ┆ …       │
│ 9990   ┆ CA-2014-110422 ┆ 21-01-2014 ┆ 23-01-2014 ┆ … ┆ 25.248  ┆ 3        ┆ 0.2      ┆ 4.1028  │
│ 9991   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 91.96   ┆ 2        ┆ 0.0      ┆ 15.6332 │
│ 9992   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 258.576 ┆ 2        ┆ 0.2      ┆ 19.3932 │
│ 9993   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 29.6    ┆ 4        ┆ 0.0      ┆ 13.32   │
│ 9994   ┆ CA-2017-119914 ┆ 04-05-2017 ┆ 09-05-2017 ┆ … ┆ 243.16  ┆ 2        ┆ 0.0      ┆ 72.948  │
└────────┴────────────────┴────────────┴────────────┴───┴─────────┴──────────┴──────────┴─────────┘

In [12]:
df.drop_nulls()

shape: (9_989, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬─────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales   ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---     ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64     ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪═════════╪══════════╪══════════╪═════════╡
│ 2      ┆ CA-2016-152156 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94  ┆ 3        ┆ 0.0      ┆ 219.582 │
│ 6      ┆ CA-2014-115812 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 48.86   ┆ 7        ┆ 0.0      ┆ 14.1694 │
│ 7      ┆ CA-2014-115812 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 7.28    ┆ 4        ┆ 0.0      ┆ 1.9656  │
│ 9      ┆ CA-2014-115812 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 18.504  ┆ 3        ┆ 0.2      ┆ 5.7825  │
│ 10     ┆ CA-2014-115812 ┆ 09-06-2014 ┆ 14-06-2014 ┆ … ┆ 114.9   ┆ 5        ┆ 0.0      ┆ 34.47   │
│ …      ┆ …              ┆ …          ┆ …          ┆ … ┆ …       ┆ …        ┆ …        ┆ …       │
│ 9990   ┆ CA-2014-110422 ┆ 21-01-2014 ┆ 23-01-2014 ┆ … ┆ 25.248  ┆ 3        ┆ 0.2      ┆ 4.1028  │
│ 9991   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 91.96   ┆ 2        ┆ 0.0      ┆ 15.6332 │
│ 9992   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 258.576 ┆ 2        ┆ 0.2      ┆ 19.3932 │
│ 9993   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 29.6    ┆ 4        ┆ 0.0      ┆ 13.32   │
│ 9994   ┆ CA-2017-119914 ┆ 04-05-2017 ┆ 09-05-2017 ┆ … ┆ 243.16  ┆ 2        ┆ 0.0      ┆ 72.948  │
└────────┴────────────────┴────────────┴────────────┴───┴─────────┴──────────┴──────────┴─────────┘

# Replace

In [13]:
data = {
     'Score': [88, 82, 75, 90, 80],
    'Name': ['Alice',  'Bob', 'Charlie', 'Bob', 'Alice'],
    'Age': [25, None, 35, None, None]
}
ddf = pl.DataFrame(data)
ddf

shape: (5, 3)
┌───────┬─────────┬──────┐
│ Score ┆ Name    ┆ Age  │
│ ---   ┆ ---     ┆ ---  │
│ i64   ┆ str     ┆ i64  │
╞═══════╪═════════╪══════╡
│ 88    ┆ Alice   ┆ 25   │
│ 82    ┆ Bob     ┆ null │
│ 75    ┆ Charlie ┆ 35   │
│ 90    ┆ Bob     ┆ null │
│ 80    ┆ Alice   ┆ null │
└───────┴─────────┴──────┘

In [14]:
ddf= ddf.with_columns(
    pl.col('Name').fill_null('Unknown'),
    pl.col('Age').fill_null(0),
    pl.col('Score').fill_null(1)
)
ddf

shape: (5, 3)
┌───────┬─────────┬─────┐
│ Score ┆ Name    ┆ Age │
│ ---   ┆ ---     ┆ --- │
│ i64   ┆ str     ┆ i64 │
╞═══════╪═════════╪═════╡
│ 88    ┆ Alice   ┆ 25  │
│ 82    ┆ Bob     ┆ 0   │
│ 75    ┆ Charlie ┆ 35  │
│ 90    ┆ Bob     ┆ 0   │
│ 80    ┆ Alice   ┆ 0   │
└───────┴─────────┴─────┘

In [15]:
#Forwrad  startegy reply current null with last nul null value
ddf = pl.DataFrame(data)
ddf.with_columns(
    pl.col('Age').fill_null(strategy='forward'),
)

shape: (5, 3)
┌───────┬─────────┬─────┐
│ Score ┆ Name    ┆ Age │
│ ---   ┆ ---     ┆ --- │
│ i64   ┆ str     ┆ i64 │
╞═══════╪═════════╪═════╡
│ 88    ┆ Alice   ┆ 25  │
│ 82    ┆ Bob     ┆ 25  │
│ 75    ┆ Charlie ┆ 35  │
│ 90    ┆ Bob     ┆ 35  │
│ 80    ┆ Alice   ┆ 35  │
└───────┴─────────┴─────┘

In [16]:
ddf.with_columns(
    pl.col('Age').fill_null(strategy='backward'), #limit=1 fill with only one column then use next valid record
)

shape: (5, 3)
┌───────┬─────────┬──────┐
│ Score ┆ Name    ┆ Age  │
│ ---   ┆ ---     ┆ ---  │
│ i64   ┆ str     ┆ i64  │
╞═══════╪═════════╪══════╡
│ 88    ┆ Alice   ┆ 25   │
│ 82    ┆ Bob     ┆ 35   │
│ 75    ┆ Charlie ┆ 35   │
│ 90    ┆ Bob     ┆ null │
│ 80    ┆ Alice   ┆ null │
└───────┴─────────┴──────┘

In [17]:
ddf.with_columns(
    pl.col('Age').fill_null(strategy='forward').over('Name')
)

shape: (5, 3)
┌───────┬─────────┬──────┐
│ Score ┆ Name    ┆ Age  │
│ ---   ┆ ---     ┆ ---  │
│ i64   ┆ str     ┆ i64  │
╞═══════╪═════════╪══════╡
│ 88    ┆ Alice   ┆ 25   │
│ 82    ┆ Bob     ┆ null │
│ 75    ┆ Charlie ┆ 35   │
│ 90    ┆ Bob     ┆ null │
│ 80    ┆ Alice   ┆ 25   │
└───────┴─────────┴──────┘

In [19]:
#Interpolation methods works well where data changes linearly over time
ddf.with_columns(
    pl.col('Age').interpolate()
)

shape: (5, 3)
┌───────┬─────────┬──────┐
│ Score ┆ Name    ┆ Age  │
│ ---   ┆ ---     ┆ ---  │
│ i64   ┆ str     ┆ f64  │
╞═══════╪═════════╪══════╡
│ 88    ┆ Alice   ┆ 25.0 │
│ 82    ┆ Bob     ┆ 30.0 │
│ 75    ┆ Charlie ┆ 35.0 │
│ 90    ┆ Bob     ┆ null │
│ 80    ┆ Alice   ┆ null │
└───────┴─────────┴──────┘