In [1]:
import pandas as pd

titanic = pd.read_csv("../data/titanic.csv")
houses = pd.read_csv('../data/kc_house_data.csv')
netflix = pd.read_csv('../data/netflix_titles.csv', sep='|', index_col=0)
btc = pd.read_csv('../data/coin_Bitcoin.csv')
countries = pd.read_csv('../data/world-happiness-report-2021.csv')

In [3]:
#Series.astype  object,int, float, category
titanic.age.replace(['?'], [None], inplace=True)

In [5]:
titanic['age'] = titanic.age.astype('float')

In [7]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
dtypes: float64(1), int64(4), object(9)
memory usage: 143.3+ KB

In [9]:
titanic.age.mean()

np.float64(29.8811345124283)

In [12]:
#category is used in columns with a set of possible values(enum)
titanic['sex'] = titanic['sex'].astype('category')

In [13]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   category
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
dtypes: category(1), float64(1), int64(4), object(8)
memory usage: 134.5+ KB

In [14]:
#setting sex to MALE changes type back to object titanic[''sex'] = 'MALE'
#this is due to it being different from  the category values
titanic['embarked'] = titanic['embarked'].astype('category')

In [16]:
#to_numeric  pandas.to_numeric converts argument to float or int based on values
#errors ignore, raise, coerce default raise invalid raises exception. ignore returns inpur
#coerce returns NaN   takes in a series
titanic = pd.read_csv("../data/titanic.csv")
titanic['age'] = pd.to_numeric(titanic['age'], errors='coerce')

In [17]:
titanic['age'].describe()

count    1046.000000
mean       29.881135
std        14.413500
min         0.166700
25%        21.000000
50%        28.000000
75%        39.000000
max        80.000000
Name: age, dtype: float64

In [18]:
#
games = pd.read_csv('../data/game_stats.csv')

In [21]:
games.isna()

    name  league  points  assists  rebounds
0  False   False   False    False     False
1  False    True   False     True     False
2  False   False    True     True      True
3  False   False   False     True     False
4  False    True   False     True      True
5  False   False   False    False     False
6   True    True    True     True      True

In [22]:
games.league.isna()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
Name: league, dtype: bool

In [23]:
games[games.league.isna()]

       name league  points  assists  rebounds
1    jessie    NaN    10.0      NaN       2.0
4  timothee    NaN     8.0      NaN       NaN
6       NaN    NaN     NaN      NaN       NaN

In [24]:
#dropna   Series.dropna  DataFrame.dropna
games['assists'].dropna()

0    5.0
5    8.0
Name: assists, dtype: float64

In [35]:
todrop = games['assists']

In [36]:
todrop

0    5.0
1    NaN
2    NaN
3    NaN
4    NaN
5    8.0
6    NaN
Name: assists, dtype: float64

In [37]:
todrop.dropna(inplace=True)

In [38]:
todrop

0    5.0
5    8.0
Name: assists, dtype: float64

In [39]:
games['assists']

0    5.0
1    NaN
2    NaN
3    NaN
4    NaN
5    8.0
6    NaN
Name: assists, dtype: float64

In [40]:
#on DataFrame  it removes rows or colums
games.dropna()  #drops rows with Nan based on condiiton given   drops all rows with Nan values how=any default

    name league  points  assists  rebounds
0    bob    nba    22.0      5.0      10.0
5  steph    nba    49.0      8.0      10.0

In [42]:
games.dropna(how='all')

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie         NaN    10.0      NaN       2.0
2       stu  euroleague     NaN      NaN       NaN
3   jackson         aba     9.0      NaN       2.0
4  timothee         NaN     8.0      NaN       NaN
5     steph         nba    49.0      8.0      10.0

In [43]:
games.dropna(subset=['league'])

      name      league  points  assists  rebounds
0      bob         nba    22.0      5.0      10.0
2      stu  euroleague     NaN      NaN       NaN
3  jackson         aba     9.0      NaN       2.0
5    steph         nba    49.0      8.0      10.0

In [46]:
games.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [47]:
#fillna
games.fillna(0)

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie           0    10.0      0.0       2.0
2       stu  euroleague     0.0      0.0       0.0
3   jackson         aba     9.0      0.0       2.0
4  timothee           0     8.0      0.0       0.0
5     steph         nba    49.0      8.0      10.0
6         0           0     0.0      0.0       0.0

In [48]:
games.league.fillna('amateur')

0           nba
1       amateur
2    euroleague
3           aba
4       amateur
5           nba
6       amateur
Name: league, dtype: object

In [50]:
games.fillna({'points': 0, 'league': 'amateur', 'assists': 'none'})

       name      league  points assists  rebounds
0       bob         nba    22.0     5.0      10.0
1    jessie     amateur    10.0    none       2.0
2       stu  euroleague     0.0    none       NaN
3   jackson         aba     9.0    none       2.0
4  timothee     amateur     8.0    none       NaN
5     steph         nba    49.0     8.0      10.0
6       NaN     amateur     0.0    none       NaN

In [51]:
sales = pd.read_csv('../data/sales.csv')

In [52]:
#fill with value from another row
sales['shipping_zip'].fillna(sales['billing_zip'])

0    81220.0
1    94931.0
2    92625.0
3    10003.0
4    92660.0
5        NaN
6    60007.0
Name: shipping_zip, dtype: float64