In [1]:
import pandas as pd

s1 = pd.Series(['a', 'b', 'c'])
s2 = pd.Series(['d', 'e', 'z', 'l'])

pd.concat([s1, s2])

0    a
1    b
2    c
0    d
1    e
2    z
3    l
dtype: object

In [2]:
pd.concat([s2, s1]) #Index for each row is preserved

0    d
1    e
2    z
3    l
0    a
1    b
2    c
dtype: object

In [3]:
pd.concat([s2, s1], ignore_index=True)

0    d
1    e
2    z
3    l
4    a
5    b
6    c
dtype: object

In [5]:
pd.concat([s2, s1, pd.Series([23, 29, 34, 56])])

0     d
1     e
2     z
3     l
0     a
1     b
2     c
0    23
1    29
2    34
3    56
dtype: object

In [6]:
c1 = pd.Series(['red', 'orange', 'yellow'])
c2 = pd.Series(['green', 'blue', 'purple'])
pd.concat([c1, c2], axis=1) #paring is by index

        0       1
0     red   green
1  orange    blue
2  yellow  purple

In [7]:
fruits = pd.Series(
    data=['apple', 'banana', 'cherry'],
    index=['a', 'b', 'c']
)
animals = pd.Series(
    data=['badger', 'cougar', 'anaconda'],
    index=['b', 'c', 'a']
)

pd.concat([fruits, animals])

a       apple
b      banana
c      cherry
b      badger
c      cougar
a    anaconda
dtype: object

In [8]:
pd.concat([fruits, animals], axis=1)

        0         1
a   apple  anaconda
b  banana    badger
c  cherry    cougar

In [9]:
pd.concat([fruits, animals], axis=1, keys=['fruit', 'animal'])

    fruit    animal
a   apple  anaconda
b  banana    badger
c  cherry    cougar

In [10]:
pd.concat([fruits, animals], keys=['fruit', 'animal'])

fruit   a       apple
        b      banana
        c      cherry
animal  b      badger
        c      cougar
        a    anaconda
dtype: object

In [11]:
#Inner vs Outer Joins
fruits = pd.Series(
    data=['apple', 'banana', 'cherry', 'dorian'],
    index=['a', 'b', 'c', 'd']
)
animals = pd.Series(
    data=['badger', 'cougar', 'anaconda', 'elk', 'pika'],
    index=['b', 'c', 'a', 'e', 'p']
)

pd.concat([fruits, animals], ignore_index=True)

0       apple
1      banana
2      cherry
3      dorian
4      badger
5      cougar
6    anaconda
7         elk
8        pika
dtype: object

In [12]:
pd.concat([fruits, animals], axis=1)

        0         1
a   apple  anaconda
b  banana    badger
c  cherry    cougar
d  dorian       NaN
e     NaN       elk
p     NaN      pika

In [13]:
pd.concat([fruits, animals], axis=1, join='inner') #outer is default

        0         1
a   apple  anaconda
b  banana    badger
c  cherry    cougar

In [24]:
#Concatenating Dataframes by column
harvest_21 = pd.DataFrame(
    [['potatoes', 900], ['garlic', 1350], ['onions', 875]],
    columns=['crop', 'qty']
)

harvest_22 = pd.DataFrame(
    [['garlic', 1600], ['spinach', 560], ['turnips', 999], ['onions', 1000]],
    columns=['crop', 'qty']
)
harvest_21

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875

In [15]:
harvest_22

      crop   qty
0   garlic  1600
1  spinach   560
2  turnips   999
3   onions  1000

In [25]:
pd.concat([harvest_21, harvest_22], ignore_index=True)

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875
3    garlic  1600
4   spinach   560
5   turnips   999
6    onions  1000

In [20]:
pd.concat([harvest_21, harvest_22], keys=[2021, 2022])

            crop   qty
2021 0  potatoes   900
     1    garlic  1350
     2     nions   875
2022 0    garlic  1600
     1   spinach   560
     2   turnips   999
     3    onions  1000

In [26]:
harvest_23 = pd.DataFrame(
    [['potatoes', 900, 500], ['garlic', 1350, 1200], ['onions', 875, 950]],
    columns=['crop', 'qty', 'profit']
)

pd.concat([harvest_21, harvest_22, harvest_23])

       crop   qty  profit
0  potatoes   900     NaN
1    garlic  1350     NaN
2    onions   875     NaN
0    garlic  1600     NaN
1   spinach   560     NaN
2   turnips   999     NaN
3    onions  1000     NaN
0  potatoes   900   500.0
1    garlic  1350  1200.0
2    onions   875   950.0

In [27]:
pd.concat([harvest_21, harvest_22, harvest_23], join='inner')

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875
0    garlic  1600
1   spinach   560
2   turnips   999
3    onions  1000
0  potatoes   900
1    garlic  1350
2    onions   875

In [29]:
#Concat by Index

livestock = pd.DataFrame(
    [['pasture', 9], ['stable', 3], ['coop', 34]],
    columns=['location', 'qty'],
    index=['alpaca', 'horse', 'chicken']
)

weights = pd.DataFrame(
    [[4, 10], [900, 2000], [1.2, 4], [110, 150]],
    columns=['min_weight', 'max_weight'],
    index=['chicken', 'horse', 'duck', 'alpaca']
)
livestock

        location  qty
alpaca   pasture    9
horse     stable    3
chicken     coop   34

In [30]:
weights

         min_weight  max_weight
chicken         4.0          10
horse         900.0        2000
duck            1.2           4
alpaca        110.0         150

In [31]:
pd.concat([livestock, weights])

        location   qty  min_weight  max_weight
alpaca   pasture   9.0         NaN         NaN
horse     stable   3.0         NaN         NaN
chicken     coop  34.0         NaN         NaN
chicken      NaN   NaN         4.0        10.0
horse        NaN   NaN       900.0      2000.0
duck         NaN   NaN         1.2         4.0
alpaca       NaN   NaN       110.0       150.0

In [32]:
pd.concat([livestock, weights], axis=1)

        location   qty  min_weight  max_weight
alpaca   pasture   9.0       110.0         150
horse     stable   3.0       900.0        2000
chicken     coop  34.0         4.0          10
duck         NaN   NaN         1.2           4

In [33]:
pd.concat([livestock, weights], axis=1, join='inner')

        location  qty  min_weight  max_weight
alpaca   pasture    9       110.0         150
horse     stable    3       900.0        2000
chicken     coop   34         4.0          10

In [34]:
#DF.merge
teams = pd.DataFrame(
    [
        ["Suns", "Phoenix", 20, 4], 
        ["Mavericks", "Dallas", 11,12], 
        ["Rockets", "Houston", 7, 16],
        ['Nuggets', "Denver", 11, 12]
    ], 
    columns=["team", "city", "wins", "losses"]
)

cities = pd.DataFrame(
    [
        ["Houston", "Texas", 2310000], 
        ["Phoenix", "Arizona", 1630000], 
        ["San Diego", "California", 1410000],
        ["Dallas", "Texas", 1310000]
    ],
    columns=["city", "state", "population"]
)

In [35]:
teams

        team     city  wins  losses
0       Suns  Phoenix    20       4
1  Mavericks   Dallas    11      12
2    Rockets  Houston     7      16
3    Nuggets   Denver    11      12

In [36]:
cities

        city       state  population
0    Houston       Texas     2310000
1    Phoenix     Arizona     1630000
2  San Diego  California     1410000
3     Dallas       Texas     1310000

In [38]:
teams.merge(cities) #Used city as it was in common

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

In [40]:
teams.merge(cities, on='city') #inner =default hoe=inner

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

In [42]:
teams.merge(cities, how='left')#teams = left

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona   1630000.0
1  Mavericks   Dallas    11      12    Texas   1310000.0
2    Rockets  Houston     7      16    Texas   2310000.0
3    Nuggets   Denver    11      12      NaN         NaN

In [43]:
teams.merge(cities, how='right')

        team       city  wins  losses       state  population
0    Rockets    Houston   7.0    16.0       Texas     2310000
1       Suns    Phoenix  20.0     4.0     Arizona     1630000
2        NaN  San Diego   NaN     NaN  California     1410000
3  Mavericks     Dallas  11.0    12.0       Texas     1310000

In [44]:
teams.merge(cities, how='outer')

        team       city  wins  losses       state  population
0  Mavericks     Dallas  11.0    12.0       Texas   1310000.0
1    Nuggets     Denver  11.0    12.0         NaN         NaN
2    Rockets    Houston   7.0    16.0       Texas   2310000.0
3       Suns    Phoenix  20.0     4.0     Arizona   1630000.0
4        NaN  San Diego   NaN     NaN  California   1410000.0

In [41]:
midterms = pd.DataFrame(
    [['alex', 'padilla', 92], ['rayna', 'wilson', 83], ['juan', 'gomez', 78], ['angela', 'smith', 66],['stephen', 'yu', 98]], 
    columns=['first', 'last', 'score']
)
finals = pd.DataFrame(
    [['alex','padilla', 97, False], ['rayna', 'wilson', 88, False], ['alex', 'smith', 86, True], ['juan', 'gomez', 71, True], ['stephen', 'yu', 78, False], ['sakura', 'steel', 100, True]], 
    columns=['first', 'last','score', 'extra_credit']
)

In [45]:
midterms

     first     last  score
0     alex  padilla     92
1    rayna   wilson     83
2     juan    gomez     78
3   angela    smith     66
4  stephen       yu     98

In [46]:
finals

     first     last  score  extra_credit
0     alex  padilla     97         False
1    rayna   wilson     88         False
2     alex    smith     86          True
3     juan    gomez     71          True
4  stephen       yu     78         False
5   sakura    steel    100          True

In [47]:
midterms.merge(finals, on='score')

  first_x last_x  score  first_y last_y  extra_credit
0    juan  gomez     78  stephen     yu         False

In [49]:
midterms.merge(finals, on='first')

     first   last_x  score_x   last_y  score_y  extra_credit
0     alex  padilla       92  padilla       97         False
1     alex  padilla       92    smith       86          True
2    rayna   wilson       83   wilson       88         False
3     juan    gomez       78    gomez       71          True
4  stephen       yu       98       yu       78         False

In [50]:
midterms.merge(finals, on=['first', 'last']) #Default sufffixes = _x, _y

     first     last  score_x  score_y  extra_credit
0     alex  padilla       92       97         False
1    rayna   wilson       83       88         False
2     juan    gomez       78       71          True
3  stephen       yu       98       78         False

In [51]:
midterms.merge(finals, on=['first', 'last'], suffixes=('_midterms', '_finals'))

     first     last  score_midterms  score_finals  extra_credit
0     alex  padilla              92            97         False
1    rayna   wilson              83            88         False
2     juan    gomez              78            71          True
3  stephen       yu              98            78         False

In [53]:
combo = midterms.merge(finals, on=['first', 'last'], suffixes=('_midterms', '_finals'))
combo['avg'] = (combo['score_midterms'] + combo['score_finals']) / 2
combo

     first     last  score_midterms  score_finals  extra_credit   avg
0     alex  padilla              92            97         False  94.5
1    rayna   wilson              83            88         False  85.5
2     juan    gomez              78            71          True  74.5
3  stephen       yu              98            78         False  88.0

In [54]:
combo.loc[combo["extra_credit"] == True, 'avg'] += 5
combo

     first     last  score_midterms  score_finals  extra_credit   avg
0     alex  padilla              92            97         False  94.5
1    rayna   wilson              83            88         False  85.5
2     juan    gomez              78            71          True  79.5
3  stephen       yu              98            78         False  88.0